mutation signupUser(
  $firstName: String!
  $lastName: String!
  $email: String!
  $password: String!
) {
  signupUser(
    firstName: $firstName
    lastName: $lastName
    email: $email
    password: $password
  ) {
    token
  }
}
